name: kennbuschphoto
favicon: null
layout_spectrum: 0.8849540129303932
typography_spectrum: 0.6576783419586718
title: Kenn Busch Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.01674867607653141
  lightness: 0.9831569301895797
  saturation: 0.2765710037201643
  rhythmicContrast: 0.7473772251978517
purpose: []
